worker_processes auto;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events { worker_connections 1024; }

http {
    access_log /dev/stdout;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 5173;
        server_name _;
        root /app/dist;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /ws {
            proxy_pass http://10.11.1.120:3001/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /api {
            proxy_pass http://10.11.1.120:3001;
        }

        location /agents {
            proxy_pass http://10.11.1.120:3001;
        }

        location /announce {
            proxy_pass http://10.11.1.120:3001;
        }
    }
}
