[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:vite]
command=node node_modules/.bin/vite preview --host 0.0.0.0 --port 5173
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:nginx]
command=nginx -c /app/nginx.conf -g "daemon off;"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
